### ISSUE TITLE
Switching to SRA with enableSingleRequest() with bulk ad config

### ISSUE THREAD

**Issue by xkema** [cobbdb/harmony#67]
@cobbdb, I tried your sample gist at [https://gist.github.com/cobbdb/31f52521cb63eaa475be1d6240b6d336](https://gist.github.com/cobbdb/31f52521cb63eaa475be1d6240b6d336) but i couldn't enable SRA mode with harmony.. I prepared a demo GitHub page at [https://xkema.github.io/untitled-harmony-sra-trial/](https://xkema.github.io/untitled-harmony-sra-trial/) in case you want to check it out again..  (_index-harmony.html_ demo still sends three separate requests while _index-gpt.html_ demo leverages all three ad slot requests in a single call)

**Comment by cobbdb** [comment]
Thanks @xkema , should be good to go now with 7.4.2 . I'm seeing correct srm behavior now with pages setup like the demo.

**Comment by xkema** [comment]
Works perfectly with 7.4.2, thanks @cobbdb
